name = "cloud-final"
compatibility_date = "2026-06-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "kelompok4_helpdesk_db"
database_id = "ed769aba-97fc-49ed-aeac-6225792f209d"
