name = "kelompok-4-helpdesk-cloudflare"
compatibility_date = "2026-06-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "kelompok4_helpdesk_db"
database_id = "REPLACE_WITH_YOUR_DATABASE_ID"
